name: Deploy Jekyll site to Github Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "main"
  cancel-in-progress: true

env:
  STEAMID: 76561198054967504

jobs:
  fetch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        game:
          - { id: 1173770, name: "ff1" }
          - { id: 1173780, name: "ff2" }
          - { id: 1173790, name: "ff3" }
          - { id: 239120, name: "ff3-3d-remake" }
          - { id: 1173800, name: "ff4" }
          - { id: 312750, name: "ff4-3d-remake" }
          - { id: 346830, name: "ff4-after-years" }
          - { id: 1173810, name: "ff5" }
          - { id: 1173820, name: "ff6" }
          - { id: 39140, name: "ff7" }
          - { id: 1608070, name: "ff7-crisis-core" }
          - { id: 1462040, name: "ff7-remake" }
          - { id: 2909400, name: "ff7-rebirth" }
          - { id: 39150, name: "ff8" }
          - { id: 1026680, name: "ff8-remastered" }
          - { id: 377840, name: "ff9" }
          - { id: 359870, name: "ff10-10-2" }
          - { id: 595520, name: "ff12" }
          - { id: 292120, name: "ff13" }
          - { id: 292140, name: "ff13-2" }
          - { id: 345350, name: "ff13-lightning-returns" }
          - { id: 637650, name: "ff15" }
          - { id: 2515020, name: "ff16" }
          - { id: 1004640, name: "fftactics" }
          - { id: 340170, name: "fftype0-hd" }
          - { id: 552700, name: "world-of-ff" }

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch Player JSON
        run: |
          curl -sf \
            "https://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v0002/?appid=${{ matrix.game.id }}&key=${{ secrets.STEAM_API_KEY }}&steamid=$STEAMID" \
            | jq -c '.' > player.json

      - name: Upload Player JSON
        uses: actions/upload-artifact@v4
        with:
          name: player-json
          path: player.json

      - name: Fetch Schema JSON
        run: |
          curl -sf \
            "https://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2/?key=${{ secrets.STEAM_API_KEY }}&appid=${{ matrix.game.id }}" \
            | jq -c '.' > schema.json

      - name: Upload Schema JSON
        uses: actions/upload-artifact@v4
        with:
          name: schema-json
          path: schema.json

  merge:
    runs-on: ubuntu-latest
    needs: fetch

    steps:
      - name: Download all Player JSON
        uses: actions/download-artifact@v4
        with:
          name: player-json
          path: ./_data/player

      - name: Download all Schema JSON
        uses: actions/download-artifact@v4
        with:
          name: schema-json
          path: ./_data/schema

      - name: Merge into player.json
        run: jq -s '.' ./_data/player/*.json > ./_data/player.json

      - name: Merge into schema.json
        run: jq -s '.' ./_data/schema/*.json > ./_data/schema.json

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: merge

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
